version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --index-date-range "2019-01-01 to 2019-03-01 by month" --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measure_*.csv

        